import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "1 Club BHU",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="bumblebee" lang="en">
      
      <body className={inter.className}>
      <ToastContainer></ToastContainer>
        {/* {children} */}
        {/* site under maintainance message
         */}
        <div className=" text-grey text-9xl h-full text-center p-3">
          Site is under maintainance. Please visit after some time.
        </div>
        </body>
    </html>
  );
}
